name: Example Workflow
on: [workflow_dispatch]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        run: cd ./.github/hello-action && npm install
      - name: Run custom action
        id: hello
        uses: ./.github/hello-action
        with:
          name: "GitHub Actions"
      - run: |
         echo ${{ vars.TEST }}
      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: "1.1.7"
      - run: terraform --version
