name: Example Workflow
on: [workflow_dispatch]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run custom action
        id: hello
        uses: ./custom-js-action
        with:
          name: "GitHub Actions"
