name: Example Workflow
permissions:
  contents: read
  packages: read
on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        options:
          - dev
          - test
  push:
    branches: [main]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: ${{inputs.Environment}}
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'
      #     cache-dependency-path: './.github/hello-action'
      # - name: Set up Node.js
      #   run: cd ./.github/hello-action && npm install
      # - name: Run custom action
      #   id: hello
      #   uses: ./.github/hello-action
      #   with:
      #     name: "GitHub Actions"
      # - uses: ./.github/actions/setup-terraform-action
      #   with:
      #     Azure_Credentials: ${{secrets.AZURE_CREDENTIALS}}
      - name: Evalute expression based on environment
        run: |
          echo "Current environment is $current_env"
        env:
          current_env: ${{inputs.Environment == 'dev' && 'ENVISDEV' || 'ENVISTEST'}}
        shell: bash
