name: Example Workflow
on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        options:
          - dev
          - test
jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: ${{inputs.Environment}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        run: cd ./.github/hello-action && npm install
      - name: Run custom action
        id: hello
        uses: ./.github/hello-action
        with:
          name: "GitHub Actions"
      - uses: ./.github/actions/setup-terraform-action
        with:
          Azure_Credentials: ${{secrets.AZURE_CREDENTIALS}}
      - name: See current working directory
        run: echo $GITHUB_WORKSPACE
