name: Self Hosted Runner Workflow
permissions:
  contents: read
  packages: read
on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        options:
          - dev
          - test

jobs:
  hello-world:
    runs-on: ${{'ubuntu-latest'}}
    environment: ${{inputs.Environment}}
    # if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: show aws cli version
        run:  aws --version && echo ${{github.head_ref}}
        shell: bash
      
