name: Self Hosted Runner Workflow
permissions:
  contents: read
  packages: read
on:
  workflow_dispatch:
    inputs:
      Environment:
        required: true
        type: choice
        options:
          - dev
          - test
        
jobs:
  hello-world:
    runs-on: ${{'self-hosted' || 'ubuntu-latest'}}
    environment: ${{inputs.Environment}}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: show aws cli version
        run:  aws --version
        shell: bash
      
